### ISSUE TITLE
Copy value buttons not working

### ISSUE THREAD

**Issue by machisuji** [nextcloud/integration_openproject#147]
Clicking on "Copy value" does not copy the value. The console shows an error.

![image](https://user-images.githubusercontent.com/158871/174262165-cbcc4bb2-7887-4591-8d7c-cc089a01b53e.png)

![image](https://user-images.githubusercontent.com/158871/174262049-083f92ff-9994-46cb-ada5-5ed72585cace.png)

**Comment by kiranparajuli589** [comment]
Hmm, it is working fine for me with NC version 25. @machisuji can you please specify the Nextcloud version you're using. We can view the NC version from the `Administration -> Overview`

**Comment by individual-it** [comment]
moved to https://community.openproject.org/projects/nextcloud-integration/work_packages/42922
