### ISSUE TITLE
add pr template

### ISSUE THREAD

**Issue by kiranparajuli589** [nextcloud/integration_openproject#154]
### purpose
- motivate people to write more descriptions in their pull requests :)
- set a boilerplate with most necessary headings like description, related, how this has been tested

**Comment by individual-it** [comment]
please create a WP for that in community.openproject.com

**Comment by kiranparajuli589** [comment]
WP created [here](https://community.openproject.org/projects/nextcloud-integration/work_packages/43830/activity?query_props=%7B%22c%22%3A%5B%22id%22%2C%22subject%22%2C%22type%22%2C%22status%22%2C%22assignee%22%5D%2C%22hi%22%3Atrue%2C%22g%22%3A%22%22%2C%22is%22%3Atrue%2C%22tv%22%3Afalse%2C%22hla%22%3A%5B%22status%22%2C%22priority%22%2C%22dueDate%22%5D%2C%22t%22%3A%22id%3Aasc%22%2C%22f%22%3A%5B%7B%22n%22%3A%22status%22%2C%22o%22%3A%22o%22%2C%22v%22%3A%5B%5D%7D%5D%2C%22pp%22%3A50%2C%22pa%22%3A2%7D)
