### ISSUE TITLE
Example setup required

### ISSUE THREAD

**Issue by Myckonid** [nextcloud/integration_openproject#2]
I tried different authorization options, I always fall into an error.
![image](https://user-images.githubusercontent.com/83160000/115986920-56e13800-a5bb-11eb-92a4-8a4b219d9a35.png)
ty very much

**Comment by eneiluj** [comment]
Hi,

Are you sure your OpenProject access token (API key) is correct?
There is no specific setup requirement on OpenProject or Nextcloud side to use this app. Just use the URL of your OpenProject instance and the access token you've created in your OpenProject account settings.

**Comment by Shifter2600** [comment]
I am having the same issue. 
My Access token is correct and it does save the connection but in the Dashboard it fails to get the Notifications.
![image](https://user-images.githubusercontent.com/12968586/116933223-7d891980-ac20-11eb-97c3-cb9e4c712df7.png)
Dashboard Error connecting to OpenProject
![image](https://user-images.githubusercontent.com/12968586/116933330-a4dfe680-ac20-11eb-8c9e-03fb6d529afa.png)

**Comment by Shifter2600** [comment]
I am able to connect using the Access Token via Postman. You can see it requires using Basic Auth and the apikey and token. Which is outline in their documentation. https://docs.openproject.org/api/example/ 
![image](https://user-images.githubusercontent.com/12968586/116938686-68b08400-ac28-11eb-85fa-10afd58ad784.png)

**Comment by seraphyn** [comment]
@Shifter2600 Have you fixed this issue?
I'm having the same problem atm and the logs do not help in any way to fix this problem.
thx in advance

**Comment by individual-it** [comment]
The current version 2.0.0 has a complete different workflow to connect. Please try it with OpenProject 12.2 and report any issue in https://community.openproject.org/projects/nextcloud-integration/work_packages
