### ISSUE TITLE
Add more informative message in the search multiselect for different state

### ISSUE THREAD

**Issue by kiranparajuli589** [nextcloud/integration_openproject#200]
The PR which allows dynamic message for the `#noResult` slot in `MultiSelect` input is merged. :confetti_ball:

Pr Link here: https://github.com/nextcloud/nextcloud-vue/pull/2533

Maybe we will get this code after the `6.0.0` release. But I'm not sure. This issue is to remind us.

With this we can now show different `multiselect` input messages with respect to the state of the search like:
- we're searching for you (if still searching).
- No results were found (if no results were found after the search).

**Comment by individual-it** [comment]
please move to community.openproject.com

**Comment by kiranparajuli589** [comment]
work package created https://community.openproject.org/projects/nextcloud-integration/work_packages/43831
