### ISSUE TITLE
http Access for testing purpose

### ISSUE THREAD

**Issue by ralfi** [nextcloud/integration_openproject#25]
Hi Devs,

please can you modify the field for the openproject URL to accept http (not only https) requests? 
This could be very helpfull for testing or temporary installations without TLS/SSL.

Thanks in advance.

**Comment by wielinde** [comment]
That issue is solved on the current `master` branch. However, the state in the `master` branch will only work, once the new "File storage" module in OpenProject is finished an released. Please stay tuned.
