### ISSUE TITLE
can't enter url with relative path

### ISSUE THREAD

**Issue by thiller2018** [nextcloud/integration_openproject#3]
The plugin doesn't allow a path like https://my.example.com/openproject

**Comment by eneiluj** [comment]
Hi, I can't reproduce the issue. I just tried and it works fine.
Are you using OAuth or a personal API token?
Do you get the "OpenProject instance not found" error when setting a personal token in NC connected accounts settings?

**Comment by wielinde** [comment]
Please also checkout my comment here https://github.com/nextcloud/integration_openproject/issues/8#issuecomment-1082762921
