### ISSUE TITLE
l10n: String parts are not available at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/integration_openproject#362]
This part is available:
https://github.com/nextcloud/integration_openproject/blob/1d67a3268eeeb3a1a46d248b379dd9fc593ac1a2/src/components/AdminSettings.vue#L508

This part is NOT available:
https://github.com/nextcloud/integration_openproject/blob/1d67a3268eeeb3a1a46d248b379dd9fc593ac1a2/src/components/AdminSettings.vue#L509

**Comment by SwikritiT** [comment]
hello, thank yo for opening this issue. For future reference please open any issue related to this integration in https://community.openproject.org/projects/nextcloud-integration/work_packages.

**Comment by SwikritiT** [comment]
Issue moved to here: https://community.openproject.org/projects/nextcloud-integration/work_packages/46668
