### ISSUE TITLE
Provide Tasks to the Nextcloud Task/Calendar App

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/integration_openproject#5]
Quite a big feature request but would it (technically) be possible to hand over the tasks from OpenProject to Nextcloud and show it there in the task and calendar app (as for example the Deck app does it)?

**Comment by wielinde** [comment]
Hey @q-wertz, indeed a big feature request. I believe the route to go would be to have OpenProject support some sort of CALDAV URL and then subscribe to that URL in your Nextcloud calendar. However, CALDAV URLs are not on the current roadmap of Nextcloud. Please find a feature request here https://community.openproject.org/projects/openproject/work_packages/22733/
