### ISSUE TITLE
Error connecting to OpenProject

### ISSUE THREAD

**Issue by AlejandroFNadal** [nextcloud/integration_openproject#8]
Hello, I am having an issue

I set up an API token in OpenProject, pasted it into the Access Token, and it says that the configuration was accepted.
![image](https://user-images.githubusercontent.com/32724827/137312606-b0878912-a54e-42bd-971a-557b26709af2.png)
However, if I try to use the extension, I get the message "Error connecting to openproject"

In the openproject logs, I get:

` /opt/openproject/app/services/scm/checkout_instructions_service.rb:48 in 'checkout_url': URI.escape is obsolete (StructuredWarnings: StandardWarning)`

In Nextcloud logs I get:

```
Warning integration_openproject OpenProject API error : Client error: GET 2021-10-14T11:39:06+00:00 http://address_here/api/v3/work_packages?filters=%5B%7B%22status%22%3A%7B%22operator%22%3A%22%21%22%2C%22values%22%3A%5B%2214%22%5D%7D%7D&sortBy=%5B%5B%22updatedAt%22%2C+%22desc%22%5D%5D

resulted in a 400 Bad Request response: {"_type":"Error", "errorIdentifier": "urn:openproject-org:api:v3:errors:InvalidQuery", "message": "Status filter has invalid (truncated...) 
```

I am running OpenProject 11.3.5 and NextCloud 21.0.4, both in Debian 10 machines.

Any suggestions or ideas? Thanks in advance :-D

**Comment by wielinde** [comment]
Hey, first of all thank you for trying the integration. 

It is half a year later... so, unless you updated them, both of your systems are not up to date. OpenProject is currently in version 12.0 and Nextcloud in version 23.

Did you also setup the OpenProject OAuth2 connection in your general Nextcloud admin settings (Settings --> Administration --> Connected accounts)?

The option to use your personal API token will get removed in the next release of this integration. Then you will only be able to authenticate per user via the OAuth2 protocol. This gives more control to the admins on who has access on and exposes which data.

**Comment by cmmata** [comment]
Hello! I have Nextcloud 24.0.4 and OpenProject 12.1.6, and I'm trying to integrate both services, but I cannot.

In the `general connected accounts`, I added the OP instance URL, client ID and client secret. In the `user connected accounts`, I added the same OP instance URL, and clicked on the connect button. But then I see the message
```
An authorization error has occurred.
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method. 
```

Do I need any extra config on OpenProject or somewhere? I don't find documentation for this.

Thank you in advance!

**Comment by cmmata** [comment]
I have updated to the latest OpenProject version, and now that the setup process is different, I am not sure if the previous message is still correct. I have commented in another issue all the details of the new error I am getting, but I am not sure if it's the same error or not
https://github.com/nextcloud/integration_openproject/issues/201#issuecomment-1217770906

**Comment by individual-it** [comment]
The current version 2.0.0 has a complete different workflow to connect, no tokens need to be copied. See: https://www.openproject.org/docs/system-admin-guide/integrations/nextcloud/
Please try it with OpenProject 12.2 and report any issue in https://community.openproject.org/projects/nextcloud-integration/work_packages
